name: order_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  http: ^0.13.3

  # The following adds fluro to your application
  fluro: ^2.0.3

  # The following adds fluttertoast
  fluttertoast: ^8.0.9

  # toast 部件
  oktoast: ^3.3.1


  # The following adds SQLite
  sqflite: ^2.0.3+1

  # The following adds path and path_provider
  path: ^1.8.1
  path_provider: ^2.0.11

  # The following adds support for UUID
  uuid: ^3.0.6

  # The following adds support for DateFormat
  intl: ^0.18.0

  shared_preferences: ^2.0.15

  # The following adds support for a simple numeric keyboard widget
  numeric_keyboard: ^1.1.0

  # The following adds support for battery indicator widget
  battery_indicator: ^0.1.1

  # The following adds support for signal strength indicator widget
  signal_strength_indicator: ^0.4.1

  # The following adds support for page indicator
  smooth_page_indicator: ^1.0.0+2

  # The following adds support for scaning qrcode & barcode
  scan: ^1.6.0

  # images_picker: ^1.2.11
  # permission_handler: ^10.2.0

  # The following adds support for display system ringtone
  flutter_ringtone_player: ^3.2.0

  # The following adds support for volume control
  perfect_volume_control: ^1.0.5

  # The following adds support for audio player
  # audioplayers: ^1.1.1

  # The following adds support for async lib
  async: ^2.9.0

  # The following adds support for ble
  flutter_blue_plus: ^1.3.1

  # 屏幕适配工具
  flutter_screenutil: ^5.6.0

  # Visiblity Detector
  visibility_detector: ^0.3.3

  # 屏幕截图工具
  # screenshot: ^1.2.3

  # 虚线边框工具
  dotted_border: ^2.0.0+3

  # pdf生成工具
  pdf: ^3.8.4

  # pdf预览工具
  printing: ^5.9.3

  # 文件打开工具
  open_file: ^3.2.1

  document_file_save_plus: ^1.0.9
  file_saver: ^0.1.1

  # pdf文件预览
  advance_pdf_viewer: ^2.0.1
  # pdfx: ^2.3.0
  sqflite_common_ffi_web: ^0.4.0

  # for snackbar
  get: ^4.6.5
  # flutter_snackbar: ^0.0.3 不支持空安全
  ftoast: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/icons/2.0x/
    - assets/icons/3.0x/
    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/
    - assets/sounds/
    - assets/pdf/
    - assets/icons/top_tip_right.png
    - assets/a.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: webfont
      fonts:
        - asset: assets/fonts/materialdesignicons-webfont.ttf

    - family: AlibabaFont
      fonts:
        - asset: assets/fonts/Alibaba-PuHuiTi-Bold.ttf
        - asset: assets/fonts/Alibaba-PuHuiTi-Heavy.ttf
        - asset: assets/fonts/Alibaba-PuHuiTi-Light.ttf
        - asset: assets/fonts/Alibaba-PuHuiTi-Medium.ttf
        - asset: assets/fonts/Alibaba-PuHuiTi-Regular.ttf


    - family: icomoon
      fonts:
        - asset: assets/fonts/icomoon.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
